In [1]:
import numpy as np

scalar = np.array(3)
vector = np.array([3, -1]) # 2차원 벡터
matrix = np.array([[-1, 3], [0,2], [7, -5]]) # 3 x 2 행렬
print(f'스칼라 모양 : {scalar.shape}')
print(f'벡터 모양 : {vector.shape}')
print(f'행렬 모양 : {matrix.shape}')

스칼라 모양 : ()
벡터 모양 : (2,)
행렬 모양 : (3, 2)


In [2]:
a = np.array([3, -1])
b = np.array([1,2])

print(f'넘파이 특성 - 벡터와 스칼라의 합: {a+1}')
print(f'벡터 스칼라곱: {2*a}')
print(f'a, b 벡터의 합: {a+b}')
print(f'a 벡터의 크기: {np.linalg.norm(a)}')  # 넘파이 내부의 linalg 클래스를 이용한 a 벡터의 크기를 출력하는 것이다.

넘파이 특성 - 벡터와 스칼라의 합: [4 0]
벡터 스칼라곱: [ 6 -2]
a, b 벡터의 합: [4 1]
a 벡터의 크기: 3.1622776601683795


In [3]:
# 모든 결과는 3*1+(-1)*2 = 1이 나와야 한다.
print(f'내적 첫 번째 방법: {np.dot(a,b)}')
print(f'내적 두 번째 방법: {a@b}')
print(f'내적 세 번째 방법: {np.sum([i*j for i,j in zip(a,b)])}')

내적 첫 번째 방법: 1
내적 두 번째 방법: 1
내적 세 번째 방법: 1


In [4]:
# 행렬 정의
a = np.array([[-1,3],[0,3],[7,-5]]) # 3x2 행렬 정의
b = np.array([[4,1,2],[3,5,-1]]) # 2x3 행렬 정의
print(f'a 행렬의 차원: {a.shape}')
print(f'b 행렬의 차원: {b.shape}')

a 행렬의 차원: (3, 2)
b 행렬의 차원: (2, 3)


In [5]:
print(f'a 행렬 스칼라 곱(x2): ')
print(f'{2*a}')

a 행렬 스칼라 곱(x2): 
[[ -2   6]
 [  0   6]
 [ 14 -10]]


In [6]:
a1 = np.random.normal(size=(3,2)) # 임의의 3 x 2 행렬 정의
print(f'a 행렬, a1 행렬의 합: ')
print(f'{a+a1}') # 결과는 시행할 때마다 달라짐

a 행렬, a1 행렬의 합: 
[[-1.23393172  3.70222432]
 [ 1.97278076  2.50693067]
 [ 8.34226376 -4.2124689 ]]


In [7]:
# a 행렬 b 행렬의 곱
print(f'행렬 곱 첫 번째 방식: ')
print(a @ b)
print(f'행렬 곱 두 번째 방식: ')
print(np.matmul(a,b))

행렬 곱 첫 번째 방식: 
[[  5  14  -5]
 [  9  15  -3]
 [ 13 -18  19]]
행렬 곱 두 번째 방식: 
[[  5  14  -5]
 [  9  15  -3]
 [ 13 -18  19]]


In [8]:
# 역행렬 실습
a = np.array([[1,3,5],[2,1,-1],[-1,3,-5]]) # 3 X 3 행렬 정의
a_inv = np.linalg.inv(a) # A의 역행렬 정의
print(f'A 행렬, A 역행렬의 곱')
print(np.matmul(a, a_inv))

A 행렬, A 역행렬의 곱
[[ 1.00000000e+00 -2.77555756e-17 -1.24900090e-16]
 [ 0.00000000e+00  1.00000000e+00  1.38777878e-17]
 [ 1.11022302e-16  2.77555756e-17  1.00000000e+00]]
